env:
  - UBUNTU_VERSION=zesty
  - LIVE_USER=fabriqueurs

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq debootstrap chroot xorriso squashfs-tools syslinux

install:
  - ./run.sh
