language: bash
sudo: required

env:
  - UBUNTU_VERSION=zesty LIVE_USER=fabriqueurs

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq debootstrap xorriso squashfs-tools syslinux

install:
  - sudo ./scripts/create_live_filesystem.sh $UBUNTU_VERSION
  - sudo ./scripts/launch_configure_system.sh $LIVE_USER
  - sudo ./scripts/create_iso_filesystem.sh
